### ISSUE TITLE
I tried to make the project and build xc9574 code but when i connect to cpc6128 no video. Is there any way to get the .jed file? thanks.

### ISSUE THREAD

**Issue by jgilcas** [revaldinho/cpc_ram_expansion#1]

**Comment by revaldinho** [comment]
I've pushed a new file to the cpc_ram_expansion/releases directory:

- cpc6128_ram512k_xc9572-10-PC44.jed

If you want to compile for the 6128 yourself make sure that the only `define set is 

`define X128  1

Optionally you can also have

`define USE6128FIRSTBANK 1

.. which makes the CPLD prefer to use the 6128's internal first bank of expansion to the external one, but in practice this makes no difference to operation at all. You always end up with the base 64K + 512K of expansion memory and you can't tell the difference between using internal and external expansion for that first bank. This was just an experimental option really and isn't implemented in the 74 series version.

Definitely though don't have any of the other options defined when targeting a 6128: ie X64, UNIV and now OVERDRIVE. These are options for a 464 specific version of the card which needs to work differently from the 6128 for reasons outlined in the wiki.

I hadn't expected anyone to want to build the CPLD version since the XC9572 itself is now an obsolete IC. I have a couple of the 74 series PCBs left over - if you'd like one of those then please PM me via the cpcwiki forum.

**Comment by revaldinho** [comment]
Did the JEDEC help?

have you mounted the box connector on the correct side of the board? The CPLD board requires this to be on the reverse side as shown in the photo on the wiki.

R

**Comment by revaldinho** [comment]
Hi

The JEDEC I provided was the 6128 (or 6128 and 464 Plus) only. I would expect this to show fails in all banks if you are using it on a 464 because the 464 does not have the hardware on the motherboard to write protect the internal memory when accessing an external bank.

The 74 series board implements the same logic  and so again is compatible with the 6128 and later models only.

Does your board work on a 6128 or have you only tried it on a 464 ?

I can upload another JEDEC which is more compatible with the 464 and implements the shadow RAM scheme. This can be built by selecting the X64 option in compile. However it only supports RAM modes C4-C7, and even then is imperfect if the video screen has been moved into the same RAM block as the expansion RAM. It's good enough to run the DK'Tronics bank switching and Silicon disk software though. It also runs a good number of 128K only games - see the thread on the cpcwiki, starting about here:

http://www.cpcwiki.eu/forum/amstrad-cpc-hardware/open-source-diy-512kb-ram-expansion/msg161457/#msg161457

I have since hacked my own CPLD board by adding some extra wires so that the '464 can backdrive the A15 and A14 pins. This improves compatibility a lot. Modes C4-7 are perfect with this and a few games which either didn't run at all or had some 'snow' on screen are running perfectly now. I think that mode C3 is working too, but to have all modes work on the '464 I need to backdrive MREQ_B also and getting the timing right for that is a bit more tricky. CPM-Plus doesn't currently work with this board, and that's my main motivation for continuing to work on it. I'm still playing with that from time to time. 

So please let me have some more details

- have you tested your board with a 6128 ? or just a 464 ?
- could you send me your memory test code so I can try it on my own board (with both machines)

I am thinking of respinning a new version of the CPLD board with my wiring hacks implemented on the board to have another go at full 464 compatibility soon. If you're interested in working on that let me know and you can have a bare PCB.

**Comment by revaldinho** [comment]
Yes.  I have some spare bare PCBs and a couple of fully assembled and tested 74 series boards available too. I would still like to help get your board working though, so perhaps you could send me one (without the XC9572 or RAM) and I can check it for hardware problems.

Send me an email - my address is on my profile page temporarily - and we can discuss/swap postal addresses etc.
